### ISSUE TITLE
can't find test library

### ISSUE THREAD

**Issue by sandofvega** [fortrabbit/interview-task-php#2]
As per requirement, `CraftPluginPackage` has `$testLibrary` property. But I can't find `test library` on the package detail API. Can you please help me to get it?

**Comment by ostark** [comment]
Hi @sandofvega 
Yes, there is no `testLibrary` property in the API response. 
I'd check for common test libraries in the require-dev section of the package.

**Comment by ostark** [comment]
I updated the readme to make clear what the expectation is:
https://github.com/fortrabbit/interview-task-php/commit/0345893a5d8d6ac5586f64a3abd936a98110a547#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
